public class TEMA1 extends javax.swing.JFrame {

    /**
     * AUTOR: noh noh marco antonio
     * Creates new form TEMA1
     */
    public TEMA1() {
        initComponents();
        
    }
    /*
        String valr = texto1.getText();
        double valr2 = Double.parseDouble(valr);
        
        String vaa = texto2.getText();
        double va = Double.parseDouble(vaa);
        
       double valorabs, valorela;
       
       valorabs = valr2 - va;
       if(valorabs < 0){
           valorabs *= -1;
       }
       
        valorela = valorabs/valr2;
       if(valorela < 0){
           valorela *= -1;
       }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Errores = new javax.swing.JLabel();
        MENU = new javax.swing.JButton();
        Valor_real = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TEXTO1 = new javax.swing.JTextField();
        TEXTO2 = new javax.swing.JTextField();
        CALCULAR_ERRORES = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TEXTO3 = new javax.swing.JTextField();
        TEXTO4 = new javax.swing.JTextField();
        OPCIONAL = new javax.swing.JLabel();
        TRUNCAMIENTO = new javax.swing.JCheckBox();
        REDONDEO = new javax.swing.JCheckBox();
        EAT = new javax.swing.JLabel();
        EAR = new javax.swing.JLabel();
        TEXTO5 = new javax.swing.JTextField();
        TEXTO6 = new javax.swing.JTextField();
        LIMPIAR_VALORES = new javax.swing.JButton();
        TEXTO_DECIMALES = new javax.swing.JLabel();
        INGRESAR_DECIMALES = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ingreso_de_valor = new javax.swing.JTextField();
        BUSCAR_VALOR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Errores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Errores.setText("BUSQUEDA DE VALORES");

        MENU.setText("MENU");
        MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENUActionPerformed(evt);
            }
        });

        Valor_real.setText("Insertar valor real: ");

        jLabel1.setText("Insertar valor aproximado: ");

        TEXTO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO1ActionPerformed(evt);
            }
        });

        TEXTO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO2ActionPerformed(evt);
            }
        });

        CALCULAR_ERRORES.setText("CALCULAR ERRORES");
        CALCULAR_ERRORES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULAR_ERRORESActionPerformed(evt);
            }
        });

        jLabel2.setText("Error absoluto:");

        jLabel3.setText("Error relativo:");

        TEXTO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO3ActionPerformed(evt);
            }
        });

        TEXTO4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO4ActionPerformed(evt);
            }
        });

        OPCIONAL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OPCIONAL.setText("ESTA PARTE ES OPCIONAL");

        TRUNCAMIENTO.setText("TRUNCAR VALOR");
        TRUNCAMIENTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRUNCAMIENTOActionPerformed(evt);
            }
        });

        REDONDEO.setText("REDONDEAR VALOR");
        REDONDEO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REDONDEOMouseClicked(evt);
            }
        });

        EAT.setText("Truncar:");

        EAR.setText("Redondear:");

        LIMPIAR_VALORES.setText("BORRAR DATOS");
        LIMPIAR_VALORES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPIAR_VALORESActionPerformed(evt);
            }
        });

        TEXTO_DECIMALES.setText("Ingresar numero de decimales:");

        INGRESAR_DECIMALES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESAR_DECIMALESActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingresar un valor:");

        ingreso_de_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso_de_valorActionPerformed(evt);
            }
        });

        BUSCAR_VALOR.setText("BUSCAR VALOR");
        BUSCAR_VALOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCAR_VALORActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CALCULAR_ERRORES, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(ingreso_de_valor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(OPCIONAL, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Valor_real, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TEXTO2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(TEXTO1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TEXTO3, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(TEXTO4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EAT, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TEXTO6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TEXTO5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(Errores, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(MENU)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TEXTO_DECIMALES, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(INGRESAR_DECIMALES, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(TRUNCAMIENTO)
                        .addGap(78, 78, 78)
                        .addComponent(REDONDEO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(LIMPIAR_VALORES, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(BUSCAR_VALOR)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Errores, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Valor_real, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXTO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXTO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CALCULAR_ERRORES)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXTO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXTO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OPCIONAL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingreso_de_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXTO_DECIMALES)
                    .addComponent(INGRESAR_DECIMALES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TRUNCAMIENTO)
                    .addComponent(REDONDEO))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EAT)
                    .addComponent(TEXTO5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EAR)
                    .addComponent(TEXTO6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUSCAR_VALOR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(LIMPIAR_VALORES)
                .addGap(6, 6, 6)
                .addComponent(MENU)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void TEXTO1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void MENUActionPerformed(java.awt.event.ActionEvent evt) {                                     
        VENTANA_PRINCIPAL regresar = new VENTANA_PRINCIPAL();
    regresar.setVisible(true);
    dispose();
    }                                    

    private void CALCULAR_ERRORESActionPerformed(java.awt.event.ActionEvent evt) {                                                 
     //conversion de string a double
     String llama1 = TEXTO1.getText();
     String llama2 = TEXTO2.getText();
     
     double valor_r = Double.parseDouble(llama1);
     double valor_a = Double.parseDouble(llama2);
     
     OPERACIONES x= new OPERACIONES();
     x.abso(valor_r, valor_a);
     //mandarlo a el nuevo texto
     String r2 = String.valueOf(x.result);
     TEXTO3.setText(String.valueOf(r2));
     String r3 = String.valueOf(x.result2);
     TEXTO4.setText(String.valueOf(r3));
     
     
     
  //   TEXTO3.setText(String.valueOf(x.result));
  //   TEXTO4.setText(String.valueOf(x.result2));
  
  
  
             
     //operacion de valor real y valor relativo
     /*double valor_abso, valor_rela;
     
     valor_abso = valor_r - valor_a;
     
     if(valor_abso < 0){
           valor_abso*= -1;
       }
       
        valor_rela = valor_abso/valor_r;
       if(valor_rela < 0){
           valor_rela *= -1;
       }*/
     
      // Double valorabsolutof= valorabsoluto.parseDouble(TEXTO3.getText());
       //double valabs = Double.parseDouble(TEXTO3.getText());
       //double valrela = Double.parseDouble(TEXTO4.getText());
       
       //Convertir de double a string
      // String volvervalor = String.valueOf(valor_abso);
        //String volvervalor2 = String.valueOf(valor_rela);
        
      
       // String text1 = TEXTO1.getText();
       //  TEXTO3.setText(text1);
    }                                                

    private void TEXTO3ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        //VALOR ABSOLUTO
        
        
    }                                      

    private void TEXTO4ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // VALOR RELATIVO
        
        
    }                                      

    private void TEXTO2ActionPerformed(java.awt.event.ActionEvent evt) {                                       
      // VALOR RELATIVO
      
      
    }                                      

    private void REDONDEOMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    } 
    
    private void BUSCAR_VALORActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // realizar operaciones de truncamiento y redondeo
       double ingreValor = Double.parseDouble(ingreso_de_valor.getText());
       int deci = Integer.parseInt(INGRESAR_DECIMALES.getText());
       
       
       if(TRUNCAMIENTO.isSelected()==true){
           
           
           
         ingreValor = Math.round(ingreValor * Math.pow(10,deci))/Math.pow(10,deci);
           
        
           String tunc = String.valueOf(ingreValor);
         TEXTO5.setText(tunc);
       }
       
       if(REDONDEO.isSelected()==true){
           
       
         
          deci *= 100;
          double iingreValor = Math.rint(ingreValor* deci)/deci;
          String xnxx = String.valueOf(iingreValor);
          TEXTO6.setText(xnxx);
       }
       
       
       
        // TODO add your handling code here:
    }                                            

    private void ingreso_de_valorActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void INGRESAR_DECIMALESActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void TRUNCAMIENTOActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void LIMPIAR_VALORESActionPerformed(java.awt.event.ActionEvent evt) {                                                
TEXTO1.setText("");
TEXTO2.setText("");
TEXTO3.setText("");
TEXTO4.setText("");
TEXTO5.setText("");
TEXTO6.setText("");
INGRESAR_DECIMALES.setText("");
ingreso_de_valor.setText("");
TRUNCAMIENTO.setSelected(false) ;
REDONDEO.setSelected(false);
        


// TODO add your handling code here:
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TEMA1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TEMA1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TEMA1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TEMA1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TEMA1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BUSCAR_VALOR;
    private javax.swing.JButton CALCULAR_ERRORES;
    private javax.swing.JLabel EAR;
    private javax.swing.JLabel EAT;
    private javax.swing.JLabel Errores;
    private javax.swing.JTextField INGRESAR_DECIMALES;
    private javax.swing.JButton LIMPIAR_VALORES;
    private javax.swing.JButton MENU;
    private javax.swing.JLabel OPCIONAL;
    private javax.swing.JCheckBox REDONDEO;
    private javax.swing.JTextField TEXTO1;
    private javax.swing.JTextField TEXTO2;
    private javax.swing.JTextField TEXTO3;
    private javax.swing.JTextField TEXTO4;
    private javax.swing.JTextField TEXTO5;
    private javax.swing.JTextField TEXTO6;
    private javax.swing.JLabel TEXTO_DECIMALES;
    private javax.swing.JCheckBox TRUNCAMIENTO;
    private javax.swing.JLabel Valor_real;
    private javax.swing.JTextField ingreso_de_valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration                   
}
